services:

  db:
    image: postgres:17

    container_name: printer-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: printer_dashboard
      POSTGRES_USER: printer
      POSTGRES_PASSWORD: printer

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:

    build: .

    container_name: printer-api

    depends_on:
      - db

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

volumes:
  postgres_data:
