from .manufacturer import manufacturer
from .department import department
from .location import location
from .printer import printer
from .cartridge import cartridge
from .printer_cartridge import printer_cartridge
from .stock import stock
from .stock_movement import stock_movement
from .repair import repair
from .user import user
